apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: addons
spec:
  generators:
    - matrix:
        generators:
          - list:
              elements:  # from /charts/
              - addonChart: external-secrets
              - addonChart: kyverno
          - clusters:
              selector:
                matchExpressions:
                - {key: 'akuity.io/argo-cd-cluster-name', operator: NotIn, values: [in-cluster]}
  template:
    metadata:
      name: 'addon-{{name}}-{{addonChart}}'
    spec:
      project: default
      source:
        helm:
          valueFiles:
          - '../../clusters/{{name}}/addons-values.yaml'
        repoURL: 'https://github.com/akuity-adv-gitops-workshop/control-plane-template'
        path: charts/{{addonChart}}
        targetRevision: HEAD
      destination:
        namespace: '{{addonChart}}'
        name: '{{name}}'
      syncPolicy:
        automated: {}
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true  # Big CRDs.