apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocon-cluster
spec:
  destination:
    name: workshop
    namespace: '*'
  project: default
  source:
    path: clusters/argocon
    repoURL: https://github.com/akuity-adv-gitops-workshop/control-plane-template
    directory:
      recurse: true
  syncPolicy:
    automated: {}